//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daste.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Desktop")]
        public string SourcePath {
            get {
                return ((string)(this["SourcePath"]));
            }
            set {
                this["SourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<YYYYper>\\<YYYYper>-<MMper>\\<YYYY><MM><DD>_<hh><mm><ss>.<ex>")]
        public string PatternMP4 {
            get {
                return ((string)(this["PatternMP4"]));
            }
            set {
                this["PatternMP4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<YYYYper>\\<YYYYper>-<MMper>\\<YYYY><MM><DD>_<hh><mm><ss>.<ex>")]
        public string PatternJPG {
            get {
                return ((string)(this["PatternJPG"]));
            }
            set {
                this["PatternJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Pictures\\Camera Roll")]
        public string DestPathMP4 {
            get {
                return ((string)(this["DestPathMP4"]));
            }
            set {
                this["DestPathMP4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Pictures\\Camera Roll")]
        public string DestPathJPG {
            get {
                return ((string)(this["DestPathJPG"]));
            }
            set {
                this["DestPathJPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Documents\\Mails")]
        public string DestPathEML {
            get {
                return ((string)(this["DestPathEML"]));
            }
            set {
                this["DestPathEML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<YYYYper>\\<YYYYper>-<MMper>\\<YYYY><MM><DD>_<hh><mm><ss>.<ex>")]
        public string PatternMOV {
            get {
                return ((string)(this["PatternMOV"]));
            }
            set {
                this["PatternMOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<YYYYper>-<MMper>\\<DDper>-<TITLE>.<ex>")]
        public string PatternEML {
            get {
                return ((string)(this["PatternEML"]));
            }
            set {
                this["PatternEML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Pictures\\Camera Roll")]
        public string DestPathMOV {
            get {
                return ((string)(this["DestPathMOV"]));
            }
            set {
                this["DestPathMOV"] = value;
            }
        }
    }
}
